/**
 * Ingredient Category Mapping
 * Keyword-based categorization for shopping list organization
 *
 * @module lib/ingredient-categories
 */

import type { IngredientCategory } from "@/types/shopping-list";

/**
 * Keyword-based category mapping
 * Order matters - first match wins
 */
const CATEGORY_KEYWORDS: Record<IngredientCategory, string[]> = {
  fruits: [
    "apple",
    "banana",
    "orange",
    "lemon",
    "lime",
    "strawberry",
    "blueberry",
    "raspberry",
    "blackberry",
    "grape",
    "watermelon",
    "melon",
    "cantaloupe",
    "honeydew",
    "pineapple",
    "mango",
    "peach",
    "pear",
    "cherry",
    "cherries",
    "avocado",
    "kiwi",
    "plum",
    "fig",
    "date",
    "raisin",
    "cranberry",
    "cranberries",
    "pomegranate",
    "coconut",
    "papaya",
    "grapefruit",
    "tangerine",
    "mandarin",
    "clementine",
    "apricot",
    "nectarine",
    "passion fruit",
    "dragon fruit",
    "lychee",
    "guava",
    "persimmon",
    "fruit",
    "berries",
    "citrus",
  ],
  vegetables: [
    "onion",
    "garlic",
    "tomato",
    "potato",
    "carrot",
    "celery",
    "cucumber",
    "pepper",
    "bell pepper",
    "lettuce",
    "spinach",
    "kale",
    "broccoli",
    "cauliflower",
    "zucchini",
    "squash",
    "eggplant",
    "mushroom",
    "corn",
    "pea",
    "peas",
    "green bean",
    "asparagus",
    "cabbage",
    "brussels",
    "artichoke",
    "beet",
    "radish",
    "leek",
    "scallion",
    "green onion",
    "shallot",
    "ginger",
    "jalapeno",
    "chili",
    "vegetable",
    "salad",
    "greens",
    "arugula",
    "chard",
    "bok choy",
    "fennel",
    "turnip",
    "parsnip",
    "rutabaga",
    "okra",
    "sweet potato",
    "yam",
    "pumpkin",
    "butternut",
    "acorn squash",
    "spaghetti squash",
  ],
  proteins: [
    "chicken",
    "beef",
    "pork",
    "lamb",
    "turkey",
    "duck",
    "fish",
    "salmon",
    "tuna",
    "cod",
    "tilapia",
    "halibut",
    "trout",
    "sardine",
    "anchovy",
    "shrimp",
    "prawn",
    "crab",
    "lobster",
    "scallop",
    "mussel",
    "clam",
    "oyster",
    "squid",
    "calamari",
    "octopus",
    "bacon",
    "sausage",
    "ham",
    "steak",
    "ground",
    "mince",
    "breast",
    "thigh",
    "wing",
    "leg",
    "loin",
    "ribs",
    "chop",
    "roast",
    "egg",
    "eggs",
    "tofu",
    "tempeh",
    "seitan",
    "protein",
    "meat",
    "poultry",
    "seafood",
  ],
  dairy: [
    "milk",
    "cream",
    "butter",
    "cheese",
    "yogurt",
    "yoghurt",
    "sour cream",
    "cottage cheese",
    "ricotta",
    "mozzarella",
    "cheddar",
    "parmesan",
    "feta",
    "brie",
    "gouda",
    "swiss",
    "cream cheese",
    "whipped cream",
    "half and half",
    "heavy cream",
    "buttermilk",
    "dairy",
    "greek yogurt",
    "kefir",
    "mascarpone",
    "provolone",
    "gruyere",
    "blue cheese",
    "goat cheese",
  ],
  grains: [
    "rice",
    "pasta",
    "noodle",
    "bread",
    "flour",
    "oat",
    "oats",
    "oatmeal",
    "quinoa",
    "barley",
    "couscous",
    "bulgur",
    "farro",
    "wheat",
    "corn meal",
    "cornmeal",
    "polenta",
    "tortilla",
    "pita",
    "naan",
    "bagel",
    "cracker",
    "cereal",
    "bun",
    "roll",
    "grain",
    "crust",
    "spaghetti",
    "penne",
    "macaroni",
    "linguine",
    "fettuccine",
    "lasagna",
    "ramen",
    "udon",
    "soba",
    "orzo",
    "risotto",
    "arborio",
    "jasmine rice",
    "basmati",
    "brown rice",
    "wild rice",
    "millet",
    "buckwheat",
    "amaranth",
  ],
  pantry: [
    "oil",
    "olive oil",
    "vegetable oil",
    "canola oil",
    "coconut oil",
    "sesame oil",
    "vinegar",
    "balsamic",
    "red wine vinegar",
    "white wine vinegar",
    "apple cider vinegar",
    "salt",
    "pepper",
    "sugar",
    "brown sugar",
    "powdered sugar",
    "honey",
    "maple syrup",
    "syrup",
    "sauce",
    "soy sauce",
    "fish sauce",
    "worcestershire",
    "hot sauce",
    "ketchup",
    "mustard",
    "mayonnaise",
    "stock",
    "broth",
    "bouillon",
    "can",
    "canned",
    "dried",
    "spice",
    "herb",
    "seasoning",
    "cumin",
    "paprika",
    "oregano",
    "basil",
    "thyme",
    "rosemary",
    "parsley",
    "cilantro",
    "dill",
    "mint",
    "sage",
    "bay leaf",
    "cinnamon",
    "nutmeg",
    "cloves",
    "allspice",
    "cardamom",
    "turmeric",
    "curry",
    "garam masala",
    "chili powder",
    "cayenne",
    "vanilla",
    "extract",
    "baking powder",
    "baking soda",
    "yeast",
    "chocolate",
    "cocoa",
    "nut",
    "almond",
    "walnut",
    "pecan",
    "cashew",
    "pistachio",
    "hazelnut",
    "macadamia",
    "peanut",
    "peanut butter",
    "almond butter",
    "seed",
    "sesame",
    "sunflower seed",
    "pumpkin seed",
    "chia",
    "flax",
    "tahini",
    "pesto",
    "paste",
    "tomato paste",
    "tomato sauce",
    "marinara",
    "salsa",
    "jam",
    "jelly",
    "preserve",
    "molasses",
    "agave",
    "stevia",
    "cornstarch",
    "arrowroot",
    "gelatin",
    "lentil",
    "lentils",
    "bean",
    "beans",
    "chickpea",
    "chickpeas",
    "black bean",
    "kidney bean",
    "navy bean",
    "pinto bean",
    "white bean",
    "cannellini",
  ],
  other: [], // Default fallback
};

/**
 * Categorize an ingredient based on its name
 * Uses keyword matching - first match wins
 *
 * @param ingredientName - The ingredient name to categorize
 * @returns The assigned category
 */
export function categorizeIngredient(
  ingredientName: string
): IngredientCategory {
  const lowerName = ingredientName.toLowerCase();

  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS) as [
    IngredientCategory,
    string[],
  ][]) {
    if (category === "other") continue;

    for (const keyword of keywords) {
      if (lowerName.includes(keyword)) {
        return category;
      }
    }
  }

  return "other";
}

/**
 * Get translation key for category label
 *
 * @param category - The category to get label for
 * @returns Translation key
 */
export function getCategoryLabel(category: IngredientCategory): string {
  return `shopping.categories.${category}`;
}

/**
 * Get all categories in display order
 */
export function getCategoriesInOrder(): IngredientCategory[] {
  return [
    "fruits",
    "vegetables",
    "proteins",
    "dairy",
    "grains",
    "pantry",
    "other",
  ];
}
