import { RecipeDifficulty, RecipeFormData } from "@/types/recipe";

const recipes = [
  // BREAKFAST RECIPES
  {
    title: "Berry Chia Overnight Oats",
    description:
      "A no-cook, creamy breakfast prepared the night before. Loaded with antioxidants from berries and omega-3s from chia seeds.",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    tags: ["breakfast", "vegetarian", "healthy", "meal-prep", "no-cook"],
    imageUrl: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf",
    ingredients: [
      { name: "Rolled Oats", amount: 0.5, unit: "cup" },
      { name: "Milk (Dairy or Plant)", amount: 0.75, unit: "cup" },
      { name: "Chia Seeds", amount: 1, unit: "tbsp" },
      { name: "Mixed Berries", amount: 0.5, unit: "cup" },
      { name: "Maple Syrup", amount: 1, unit: "tsp" },
      { name: "Vanilla Extract", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "In a jar or bowl, combine oats, chia seeds, maple syrup, vanilla, and milk.",
      "Stir well to combine.",
      "Gently fold in half of the mixed berries.",
      "Cover and refrigerate strictly for at least 4 hours, preferably overnight.",
      "In the morning, top with remaining berries and enjoy cold.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 300,
    protein: 12,
    carbs: 45,
    fat: 9,
    categoryIds: [],
  },
  {
    title: "Healthy Breakfast Burrito",
    description:
      "A satisfying wrap filled with protein-rich turkey sausage, fluffy eggs, and fresh veggies. Perfect for freezing for busy mornings.",
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    tags: ["breakfast", "protein", "meal-prep", "tex-mex"],
    imageUrl: "https://images.unsplash.com/photo-1601007787342-3a5027581179",
    ingredients: [
      { name: "Turkey Sausage", amount: 0.5, unit: "lb" },
      { name: "Eggs", amount: 6, unit: "large" },
      { name: "Spinach", amount: 2, unit: "cups" },
      { name: "Whole Wheat Tortillas", amount: 4, unit: "large" },
      { name: "Bell Pepper", amount: 1, unit: "medium" },
      { name: "Onion", amount: 0.5, unit: "medium" },
      { name: "Cheese (Optional)", amount: 0.5, unit: "cup" },
    ],
    instructions: [
      "Dice onion and bell pepper.",
      "In a skillet, cook turkey sausage until browned. Add onions and peppers, cook until soft.",
      "Whisk eggs and scramble them in the same pan with the meat and veggies.",
      "Stir in spinach until wilted.",
      "Divide mixture comfortably among tortillas. Top with cheese if using.",
      "Roll up tightly. Serve immediately or wrap in foil for freezing.",
    ],
    isPublic: true,
    difficulty: "medium" as RecipeDifficulty,
    calories: 280,
    protein: 25,
    carbs: 21,
    fat: 12,
    categoryIds: [],
  },
  {
    title: "Black Bean & Avocado Toast",
    description:
      "A fiber-packed savory breakfast featuring creamy avocado and seasoned black beans on crunchy toast.",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    tags: ["breakfast", "vegan", "high-fiber", "savory", "quick"],
    imageUrl: "https://images.unsplash.com/photo-1603046891726-36bfd957e0bf",
    ingredients: [
      { name: "Whole Grain Bread", amount: 2, unit: "slices" },
      { name: "Ripe Avocado", amount: 1, unit: "small" },
      { name: "Black Beans (canned)", amount: 0.5, unit: "cup" },
      { name: "Lime Juice", amount: 1, unit: "tsp" },
      { name: "Cumin", amount: 0.25, unit: "tsp" },
      { name: "Red Pepper Flakes", amount: 0.25, unit: "tsp" },
      { name: "Cilantro", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Toast the bread slices to your liking.",
      "Rinse and drain black beans. Warm them slightly in a small pan with cumin and a splash of water if desired.",
      "Mash avocado with lime juice, salt, and pepper.",
      "Spread avocado mash onto toast.",
      "Top with black beans.",
      "Garnish with red pepper flakes and fresh cilantro.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 340,
    protein: 14,
    carbs: 35,
    fat: 18,
    categoryIds: [],
  },
  {
    title: "Protein Power Porridge",
    description:
      "Classic warm oatmeal boosted with protein powder for sustained energy. Customizable with your favorite toppings.",
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    tags: ["breakfast", "high-protein", "vegetarian", "warm"],
    imageUrl: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf",
    ingredients: [
      { name: "Rolled Oats", amount: 0.5, unit: "cup" },
      { name: "Water or Milk", amount: 1, unit: "cup" },
      { name: "Protein Powder (Vanilla)", amount: 1, unit: "scoop" },
      { name: "Banana", amount: 0.5, unit: "medium" },
      { name: "Cinnamon", amount: 0.5, unit: "tsp" },
      { name: "Almond Butter", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Combine oats and liquid in a small pot. Bring to a boil.",
      "Reduce heat and simmer for 5-7 minutes until oats are soft.",
      "Remove from heat and let cool slightly (to prevent clumping).",
      "Stir in protein powder and cinnamon until smooth.",
      "Top with sliced banana and a drizzle of almond butter.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 380,
    protein: 25,
    carbs: 40,
    fat: 13,
    categoryIds: [],
  },
  {
    title: "Mushroom Hash with Poached Eggs",
    description:
      "A savory, nutrient-dense brunch option. Earthy mushrooms and onions topped with a perfectly runny poached egg.",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    tags: ["breakfast", "low-carb", "vegetarian", "keto-friendly"],
    imageUrl: "https://images.unsplash.com/photo-1525351440155-251d8aa9eb16",
    ingredients: [
      { name: "Mushrooms", amount: 2, unit: "cups" },
      { name: "Onion", amount: 1, unit: "small" },
      { name: "Kale or Spinach", amount: 2, unit: "cups" },
      { name: "Eggs", amount: 4, unit: "large" },
      { name: "Thyme", amount: 1, unit: "tsp" },
      { name: "Olive Oil", amount: 1, unit: "tbsp" },
      { name: "Garlic", amount: 1, unit: "clove" },
    ],
    instructions: [
      "Slice mushrooms and onions.",
      "Sauté onions in olive oil until soft.",
      "Add mushrooms and thyme, cook until browned.",
      "Add garlic and greens, cook until wilted. Season with salt and pepper.",
      "In a separate pot, poach eggs in simmering water for 3-4 minutes.",
      "Serve hash on plates topped with poached eggs.",
    ],
    isPublic: true,
    difficulty: "medium" as RecipeDifficulty,
    calories: 290,
    protein: 15,
    carbs: 15,
    fat: 17,
    categoryIds: [],
  },
  {
    title: "Healthy Homemade Granola",
    description:
      "Crunchy, golden granola sweetened naturally with maple syrup. Much better than store-bought!",
    prepTime: 10,
    cookTime: 25,
    servings: 8,
    tags: ["breakfast", "snack", "vegetarian", "meal-prep"],
    imageUrl: "https://images.unsplash.com/photo-1598514983318-2f64f8f4796c",
    ingredients: [
      { name: "Rolled Oats", amount: 3, unit: "cups" },
      { name: "Nuts (Almonds/Walnuts)", amount: 1, unit: "cup" },
      { name: "Seeds (Pumpkin/Sunflower)", amount: 0.5, unit: "cup" },
      { name: "Maple Syrup", amount: 0.5, unit: "cup" },
      { name: "Coconut Oil", amount: 0.25, unit: "cup" },
      { name: "Cinnamon", amount: 1, unit: "tsp" },
      { name: "Dried Fruit", amount: 0.5, unit: "cup" },
    ],
    instructions: [
      "Preheat oven to 325°F (165°C).",
      "Mix oats, nuts, seeds, and cinnamon in a large bowl.",
      "Whisk melted coconut oil and maple syrup together.",
      "Pour wet mixture over dry and toss to coat evenly.",
      "Spread on a baking sheet. Bake for 25-30 mins, stirring halfway.",
      "Let cool completely (it crisps as it cools). Stir in dried fruit.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 250,
    protein: 6,
    carbs: 25,
    fat: 15,
    categoryIds: [],
  },
  {
    title: "Breakfast Egg Wraps",
    description:
      "Low-carb wraps where the 'tortilla' is a thin layer of egg. Filled with fresh veggies and turkey.",
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    tags: ["breakfast", "low-carb", "keto", "high-protein", "quick"],
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641",
    ingredients: [
      { name: "Eggs", amount: 2, unit: "large" },
      { name: "Water", amount: 1, unit: "tsp" },
      { name: "Turkey Slices", amount: 2, unit: "oz" },
      { name: "Spinach", amount: 0.5, unit: "cup" },
      { name: "Cheese Slice", amount: 1, unit: "slice" },
      { name: "Avocado", amount: 0.25, unit: "medium" },
    ],
    instructions: [
      "Whisk eggs with water, salt, and pepper.",
      "Pour into a lightly oiled non-stick skillet, swirling to coat thinly like a crepe.",
      "Cook for 2-3 minutes until set. Flip carefully if needed.",
      "Remove from heat.",
      "Place cheese, turkey, spinach, and avocado slices in the center.",
      "Roll up tightly and serve instructions.",
    ],
    isPublic: true,
    difficulty: "medium" as RecipeDifficulty,
    calories: 220,
    protein: 20,
    carbs: 5,
    fat: 14,
    categoryIds: [],
  },
  {
    title: "Creamy Coconut Oatmeal",
    description:
      "Rich and creamy oatmeal made with coconut milk for a tropical twist.",
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    tags: ["breakfast", "vegan", "dairy-free", "comfort-food"],
    imageUrl: "https://images.unsplash.com/photo-1511914265872-c9ee69a47d33",
    ingredients: [
      { name: "Rolled Oats", amount: 1, unit: "cup" },
      { name: "Coconut Milk (Canned)", amount: 1, unit: "cup" },
      { name: "Water", amount: 1, unit: "cup" },
      { name: "Shredded Coconut", amount: 2, unit: "tbsp" },
      { name: "Maple Syrup", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Combine oats, coconut milk, water, and a pinch of salt in a pot.",
      "Bring to a boil, then reduce heat and simmer for 10-15 minutes.",
      "Stir occasionally until creamy.",
      "Remove from heat and sweeten with maple syrup.",
      "Top with shredded coconut before serving.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 350,
    protein: 8,
    carbs: 45,
    fat: 18,
    categoryIds: [],
  },
  {
    title: "Razzy Blue Smoothie",
    description:
      "A vibrant, antioxidant-rich smoothie blending raspberries and blueberries for a tart and sweet start.",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    tags: ["breakfast", "drink", "high-protein", "quick", "no-cook"],
    imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a9069733",
    ingredients: [
      { name: "Frozen Blueberries", amount: 0.5, unit: "cup" },
      { name: "Frozen Raspberries", amount: 0.5, unit: "cup" },
      { name: "Banana", amount: 1, unit: "small" },
      { name: "Greek Yogurt", amount: 0.5, unit: "cup" },
      { name: "Almond Milk", amount: 0.5, unit: "cup" },
      { name: "Flax Seeds", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Place all ingredients into a blender.",
      "Blend on high until smooth and creamy.",
      "Add more liquid if too thick.",
      "Pour into a glass and serve immediately.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 260,
    protein: 9,
    carbs: 45,
    fat: 7,
    categoryIds: [],
  },
  {
    title: "Cottage Cheese & Fruit Toast",
    description:
      "A high-protein savory-sweet combo. Crunchy toast topped with creamy cottage cheese and fresh fruit.",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    tags: ["breakfast", "high-protein", "quick", "vegetarian"],
    imageUrl: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0",
    ingredients: [
      { name: "Whole Grain Bread", amount: 1, unit: "slice" },
      { name: "Cottage Cheese", amount: 0.5, unit: "cup" },
      { name: "Strawberries or Peaches", amount: 0.5, unit: "cup" },
      { name: "Honey", amount: 1, unit: "tsp" },
      { name: "Cinnamon", amount: 1, unit: "pinch" },
    ],
    instructions: [
      "Toast the bread slice until golden.",
      "Spread cottage cheese generously over the toast.",
      "Top with sliced fruit.",
      "Drizzle with honey and dust with cinnamon.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 160,
    protein: 14,
    carbs: 20,
    fat: 4,
    categoryIds: [],
  },


  // LUNCH RECIPES
  {
    title: "Mediterranean Chickpea Salad",
    description:
      "Loaded with chickpeas, cucumbers, feta cheese, red onion, and tomatoes. Perfect for a quick, nutritious lunch.",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    tags: ["lunch", "salad", "vegetarian", "mediterranean", "no-cook"],
    imageUrl: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af",
    ingredients: [
      { name: "Chickpeas", amount: 2, unit: "cups" },
      { name: "Cherry Tomatoes", amount: 2, unit: "cups" },
      { name: "Cucumber", amount: 1, unit: "large" },
      { name: "Red Onion", amount: 0.5, unit: "medium" },
      { name: "Feta Cheese", amount: 1, unit: "cup" },
      { name: "Olive Oil", amount: 0.25, unit: "cup" },
      { name: "Lemon Juice", amount: 3, unit: "tbsp" },
      { name: "Fresh Parsley", amount: 0.25, unit: "cup" },
    ],
    instructions: [
      "Drain and rinse chickpeas thoroughly.",
      "Dice cucumber and halve cherry tomatoes.",
      "Thinly slice red onion.",
      "In a large bowl, combine chickpeas, tomatoes, cucumber, and onion.",
      "Crumble feta cheese over the salad.",
      "In a small bowl, whisk together olive oil and lemon juice.",
      "Pour dressing over salad and toss to combine.",
      "Garnish with fresh parsley and serve immediately or refrigerate.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 320,
    protein: 14,
    carbs: 32,
    fat: 16,
    categoryIds: [],
  },
  {
    title: "Grilled Chicken Caesar Salad",
    description:
      "Protein-rich grilled chicken with romaine lettuce, crunchy croutons and creamy Caesar dressing. A balanced and satisfying lunch.",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    tags: ["lunch", "salad", "protein", "classic"],
    imageUrl: "https://images.unsplash.com/photo-1546793665-c74683f339c1",
    ingredients: [
      { name: "Chicken Breast", amount: 2, unit: "large" },
      { name: "Romaine Lettuce", amount: 2, unit: "heads" },
      { name: "Croutons", amount: 2, unit: "cups" },
      { name: "Parmesan Cheese", amount: 0.5, unit: "cup" },
      { name: "Caesar Dressing", amount: 0.5, unit: "cup" },
      { name: "Olive Oil", amount: 2, unit: "tbsp" },
      { name: "Salt", amount: 1, unit: "tsp" },
      { name: "Black Pepper", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "Season chicken breasts with salt, pepper, and olive oil.",
      "Grill chicken over medium-high heat for 6-7 minutes per side until cooked through.",
      "Let chicken rest for 5 minutes, then slice into strips.",
      "Chop romaine lettuce and place in a large bowl.",
      "Add croutons and shaved Parmesan cheese.",
      "Drizzle with Caesar dressing and toss to combine.",
      "Top with grilled chicken slices and serve immediately.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 420,
    protein: 38,
    carbs: 24,
    fat: 20,
    categoryIds: [],
  },
  {
    title: "Caprese Sandwich",
    description:
      "A classic Italian sandwich with fresh mozzarella, ripe tomatoes, basil, and balsamic glaze on crusty bread.",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    tags: ["lunch", "sandwich", "vegetarian", "italian", "quick"],
    imageUrl: "https://images.unsplash.com/photo-1509722747041-616f39b57569",
    ingredients: [
      { name: "Ciabatta Bread", amount: 1, unit: "loaf" },
      { name: "Fresh Mozzarella", amount: 8, unit: "oz" },
      { name: "Tomatoes", amount: 2, unit: "large" },
      { name: "Fresh Basil", amount: 1, unit: "cup" },
      { name: "Balsamic Glaze", amount: 3, unit: "tbsp" },
      { name: "Olive Oil", amount: 2, unit: "tbsp" },
      { name: "Salt", amount: 0.5, unit: "tsp" },
      { name: "Black Pepper", amount: 0.25, unit: "tsp" },
    ],
    instructions: [
      "Slice ciabatta bread in half horizontally.",
      "Drizzle olive oil on both sides of the bread.",
      "Slice mozzarella and tomatoes into thick rounds.",
      "Layer mozzarella, tomatoes, and fresh basil leaves on bread.",
      "Season with salt and pepper.",
      "Drizzle with balsamic glaze.",
      "Close sandwich and cut in half to serve.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 480,
    protein: 22,
    carbs: 46,
    fat: 22,
    categoryIds: [],
  },
  {
    title: "Asian Sesame Noodle Bowl",
    description:
      "Tangy, nutty sesame dressing coats soba noodles with edamame and lots of crunchy vegetables.",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    tags: ["lunch", "asian", "noodles", "vegetarian", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    ingredients: [
      { name: "Soba Noodles", amount: 8, unit: "oz" },
      { name: "Edamame", amount: 1, unit: "cup" },
      { name: "Red Bell Pepper", amount: 1, unit: "large" },
      { name: "Carrots", amount: 2, unit: "medium" },
      { name: "Sesame Oil", amount: 3, unit: "tbsp" },
      { name: "Soy Sauce", amount: 0.25, unit: "cup" },
      { name: "Rice Vinegar", amount: 2, unit: "tbsp" },
      { name: "Sesame Seeds", amount: 2, unit: "tbsp" },
    ],
    instructions: [
      "Cook soba noodles according to package directions, then drain and rinse with cold water.",
      "Steam or boil edamame for 3-4 minutes.",
      "Julienne bell pepper and carrots into thin strips.",
      "In a small bowl, whisk together sesame oil, soy sauce, and rice vinegar.",
      "In a large bowl, combine noodles, edamame, and vegetables.",
      "Pour dressing over noodles and toss to coat evenly.",
      "Garnish with sesame seeds and serve chilled or at room temperature.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 340,
    protein: 14,
    carbs: 48,
    fat: 12,
    categoryIds: [],
  },
  {
    title: "Chicken Fajita Bowl",
    description:
      "Everything you'd normally wrap in a tortilla served over a crisp bed of greens with rice, beans, and all the toppings.",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    tags: ["lunch", "tex-mex", "protein", "bowl"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    ingredients: [
      { name: "Chicken Breast", amount: 1.5, unit: "lbs" },
      { name: "Bell Peppers", amount: 2, unit: "large" },
      { name: "Onion", amount: 1, unit: "large" },
      { name: "Rice", amount: 2, unit: "cups" },
      { name: "Black Beans", amount: 1, unit: "can" },
      { name: "Fajita Seasoning", amount: 3, unit: "tbsp" },
      { name: "Romaine Lettuce", amount: 4, unit: "cups" },
      { name: "Avocado", amount: 1, unit: "large" },
    ],
    instructions: [
      "Cook rice according to package instructions.",
      "Slice chicken into strips and toss with fajita seasoning.",
      "Slice bell peppers and onion into strips.",
      "Heat oil in a large skillet and cook chicken until done, about 6-7 minutes.",
      "Remove chicken and cook peppers and onions in the same pan.",
      "Warm black beans in a small pot.",
      "Build bowls with lettuce, rice, black beans, chicken, peppers, and onions.",
      "Top with sliced avocado and serve with lime wedges and salsa.",
    ],
    isPublic: true,
    difficulty: "medium" as RecipeDifficulty,
    calories: 520,
    protein: 42,
    carbs: 58,
    fat: 12,
    categoryIds: [],
  },
  {
    title: "Tuna Avocado Salad",
    description:
      "A fresh spin on classic tuna salad using nutrient-rich avocado instead of mayonnaise for a healthier option.",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    tags: ["lunch", "salad", "protein", "healthy", "no-cook"],
    imageUrl: "https://images.unsplash.com/photo-1559847844-5315695dadae",
    ingredients: [
      { name: "Canned Tuna", amount: 2, unit: "cans" },
      { name: "Avocado", amount: 1, unit: "large" },
      { name: "Lemon Juice", amount: 2, unit: "tbsp" },
      { name: "Red Onion", amount: 0.25, unit: "cup" },
      { name: "Celery", amount: 0.5, unit: "cup" },
      { name: "Salt", amount: 0.5, unit: "tsp" },
      { name: "Black Pepper", amount: 0.25, unit: "tsp" },
      { name: "Mixed Greens", amount: 4, unit: "cups" },
    ],
    instructions: [
      "Drain tuna well and place in a medium bowl.",
      "Mash avocado with lemon juice until smooth.",
      "Finely dice red onion and celery.",
      "Add avocado, onion, and celery to tuna and mix well.",
      "Season with salt and pepper to taste.",
      "Serve over mixed greens, with crackers, or in a sandwich.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 280,
    protein: 32,
    carbs: 12,
    fat: 14,
    categoryIds: [],
  },

  // DINNER RECIPES
  {
    title: "Marry Me Chicken Pasta",
    description:
      "Tender chicken in a creamy sun-dried tomato sauce that's so delicious it'll make anyone want to propose.",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    tags: ["dinner", "pasta", "creamy", "italian", "romantic"],
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9",
    ingredients: [
      { name: "Chicken Breast", amount: 1.5, unit: "lbs" },
      { name: "Pasta", amount: 12, unit: "oz" },
      { name: "Heavy Cream", amount: 1, unit: "cup" },
      { name: "Sun-Dried Tomatoes", amount: 0.5, unit: "cup" },
      { name: "Garlic", amount: 4, unit: "cloves" },
      { name: "Parmesan Cheese", amount: 0.5, unit: "cup" },
      { name: "Italian Seasoning", amount: 2, unit: "tsp" },
      { name: "Red Pepper Flakes", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "Cook pasta according to package directions, reserve 1 cup pasta water.",
      "Season chicken with salt, pepper, and Italian seasoning.",
      "Sear chicken in olive oil until golden and cooked through, about 6-7 minutes per side.",
      "Remove chicken and slice into strips.",
      "In the same pan, sauté minced garlic for 1 minute.",
      "Add sun-dried tomatoes, heavy cream, and Parmesan cheese.",
      "Simmer until sauce thickens, about 5 minutes.",
      "Add pasta and chicken to the sauce, tossing to coat.",
      "Add pasta water if needed to adjust consistency.",
      "Garnish with fresh basil and serve hot.",
    ],
    isPublic: true,
    difficulty: "medium" as RecipeDifficulty,
    calories: 680,
    protein: 46,
    carbs: 52,
    fat: 32,
    categoryIds: [],
  },
  {
    title: "Beef Stir-Fry with Vegetables",
    description:
      "Sweet and spicy beef with crisp vegetables in a savory sauce. Quick and perfect for busy weeknights.",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    tags: ["dinner", "asian", "beef", "quick", "stir-fry"],
    imageUrl: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143",
    ingredients: [
      { name: "Beef Sirloin", amount: 1, unit: "lb" },
      { name: "Broccoli Florets", amount: 2, unit: "cups" },
      { name: "Bell Peppers", amount: 2, unit: "large" },
      { name: "Snap Peas", amount: 1, unit: "cup" },
      { name: "Soy Sauce", amount: 0.25, unit: "cup" },
      { name: "Brown Sugar", amount: 2, unit: "tbsp" },
      { name: "Ginger", amount: 1, unit: "tbsp" },
      { name: "Garlic", amount: 3, unit: "cloves" },
    ],
    instructions: [
      "Slice beef thinly against the grain.",
      "Cut bell peppers into strips and separate broccoli into florets.",
      "In a small bowl, mix soy sauce, brown sugar, minced ginger, and garlic.",
      "Heat oil in a wok or large skillet over high heat.",
      "Stir-fry beef for 2-3 minutes until browned, then remove.",
      "Add vegetables to the wok and stir-fry for 3-4 minutes.",
      "Return beef to the wok and pour in sauce.",
      "Toss everything together and cook for 2 more minutes.",
      "Serve immediately over steamed rice.",
    ],
    isPublic: true,
    difficulty: "medium" as RecipeDifficulty,
    calories: 380,
    protein: 32,
    carbs: 28,
    fat: 16,
    categoryIds: [],
  },
  {
    title: "Baked Salmon with Lemon Dill",
    description:
      "Flaky, tender salmon seasoned with fresh lemon and dill. A healthy and elegant dinner that's ready in 20 minutes.",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    tags: ["dinner", "seafood", "healthy", "quick", "gluten-free"],
    imageUrl: "https://images.unsplash.com/photo-1485921325833-c519f76c4927",
    ingredients: [
      { name: "Salmon Fillets", amount: 4, unit: "6oz pieces" },
      { name: "Lemon", amount: 2, unit: "large" },
      { name: "Fresh Dill", amount: 0.25, unit: "cup" },
      { name: "Garlic", amount: 3, unit: "cloves" },
      { name: "Olive Oil", amount: 3, unit: "tbsp" },
      { name: "Salt", amount: 1, unit: "tsp" },
      { name: "Black Pepper", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "Preheat oven to 400°F and line a baking sheet with parchment paper.",
      "Place salmon fillets skin-side down on the prepared sheet.",
      "Drizzle with olive oil and season with salt and pepper.",
      "Top each fillet with minced garlic, fresh dill, and lemon slices.",
      "Bake for 15-20 minutes until salmon flakes easily with a fork.",
      "Squeeze fresh lemon juice over cooked salmon.",
      "Serve with roasted vegetables or a fresh salad.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 340,
    protein: 38,
    carbs: 4,
    fat: 19,
    categoryIds: [],
  },
  {
    title: "Classic Chicken Curry",
    description:
      "Hearty and flavorful Indian-inspired curry with tender chicken in a rich, spiced tomato sauce. Comfort food at its finest.",
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    tags: ["dinner", "indian", "curry", "spicy", "comfort-food"],
    imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db",
    ingredients: [
      { name: "Chicken Thighs", amount: 2, unit: "lbs" },
      { name: "Onion", amount: 1, unit: "large" },
      { name: "Tomato Sauce", amount: 2, unit: "cups" },
      { name: "Coconut Milk", amount: 1, unit: "can" },
      { name: "Curry Powder", amount: 3, unit: "tbsp" },
      { name: "Garlic", amount: 4, unit: "cloves" },
      { name: "Ginger", amount: 2, unit: "tbsp" },
      { name: "Cilantro", amount: 0.5, unit: "cup" },
    ],
    instructions: [
      "Cut chicken into bite-sized pieces and season with salt.",
      "Dice onion and mince garlic and ginger.",
      "Heat oil in a large pot over medium heat.",
      "Brown chicken pieces for 5 minutes, then remove from pot.",
      "Sauté onion, garlic, and ginger until softened.",
      "Add curry powder and cook for 1 minute until fragrant.",
      "Pour in tomato sauce and coconut milk, stirring to combine.",
      "Return chicken to pot and simmer for 20 minutes.",
      "Garnish with fresh cilantro and serve over basmati rice.",
    ],
    isPublic: true,
    difficulty: "medium" as RecipeDifficulty,
    calories: 420,
    protein: 34,
    carbs: 18,
    fat: 24,
    categoryIds: [],
  },
  {
    title: "Vegetarian Lentil Soup",
    description:
      "Warm and hearty soup packed with protein-rich lentils and vegetables. Perfect for cold evenings.",
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    tags: ["dinner", "soup", "vegetarian", "healthy", "comfort-food"],
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd",
    ingredients: [
      { name: "Green Lentils", amount: 1.5, unit: "cups" },
      { name: "Carrots", amount: 3, unit: "medium" },
      { name: "Celery", amount: 3, unit: "stalks" },
      { name: "Onion", amount: 1, unit: "large" },
      { name: "Vegetable Broth", amount: 6, unit: "cups" },
      { name: "Tomato Paste", amount: 2, unit: "tbsp" },
      { name: "Cumin", amount: 1, unit: "tsp" },
      { name: "Bay Leaves", amount: 2, unit: "leaves" },
    ],
    instructions: [
      "Rinse lentils and set aside.",
      "Dice carrots, celery, and onion into small pieces.",
      "Heat olive oil in a large pot over medium heat.",
      "Sauté onion, carrots, and celery for 5 minutes until softened.",
      "Add tomato paste and cumin, cooking for 1 minute.",
      "Pour in vegetable broth and add lentils and bay leaves.",
      "Bring to a boil, then reduce heat and simmer for 35-40 minutes.",
      "Remove bay leaves, season with salt and pepper.",
      "Serve hot with crusty bread.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 240,
    protein: 14,
    carbs: 42,
    fat: 3,
    categoryIds: [],
  },
  {
    title: "Honey Garlic Glazed Chicken Thighs",
    description:
      "Succulent chicken thighs with a sticky-sweet honey garlic glaze. Simple enough for weeknights, impressive enough for guests.",
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    tags: ["dinner", "chicken", "easy", "sweet", "glazed"],
    imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6",
    ingredients: [
      { name: "Chicken Thighs", amount: 8, unit: "bone-in" },
      { name: "Honey", amount: 0.33, unit: "cup" },
      { name: "Soy Sauce", amount: 0.25, unit: "cup" },
      { name: "Garlic", amount: 6, unit: "cloves" },
      { name: "Ginger", amount: 1, unit: "tbsp" },
      { name: "Rice Vinegar", amount: 2, unit: "tbsp" },
      { name: "Sesame Seeds", amount: 1, unit: "tbsp" },
      { name: "Green Onions", amount: 3, unit: "stalks" },
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Pat chicken thighs dry and season with salt and pepper.",
      "In a bowl, whisk together honey, soy sauce, minced garlic, ginger, and rice vinegar.",
      "Place chicken in a baking dish and pour half the glaze over top.",
      "Bake for 25 minutes, then brush with remaining glaze.",
      "Continue baking for 10 more minutes until chicken reaches 165°F.",
      "Garnish with sesame seeds and sliced green onions.",
      "Serve with steamed rice and vegetables.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 480,
    protein: 36,
    carbs: 26,
    fat: 26,
    categoryIds: [],
  },
  {
    title: "Shrimp and Broccoli Stir-Fry",
    description:
      "Light yet satisfying Asian-inspired dish with tender shrimp and crisp broccoli in a savory sauce.",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    tags: ["dinner", "seafood", "asian", "quick", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1633504581786-316c8002b1b9",
    ingredients: [
      { name: "Large Shrimp", amount: 1, unit: "lb" },
      { name: "Broccoli Florets", amount: 4, unit: "cups" },
      { name: "Garlic", amount: 4, unit: "cloves" },
      { name: "Soy Sauce", amount: 3, unit: "tbsp" },
      { name: "Oyster Sauce", amount: 2, unit: "tbsp" },
      { name: "Sesame Oil", amount: 1, unit: "tbsp" },
      { name: "Cornstarch", amount: 1, unit: "tsp" },
      { name: "Red Pepper Flakes", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "Peel and devein shrimp, pat dry with paper towels.",
      "Blanch broccoli in boiling water for 2 minutes, then drain.",
      "Mix soy sauce, oyster sauce, sesame oil, and cornstarch in a small bowl.",
      "Heat oil in a wok or large skillet over high heat.",
      "Stir-fry shrimp for 2-3 minutes until pink, then remove.",
      "Add minced garlic and red pepper flakes, cooking for 30 seconds.",
      "Add broccoli and stir-fry for 2 minutes.",
      "Return shrimp to wok, pour in sauce, and toss for 1 minute.",
      "Serve immediately over rice or noodles.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 210,
    protein: 28,
    carbs: 14,
    fat: 6,
    categoryIds: [],
  },
  {
    title: "Classic Spaghetti Bolognese",
    description:
      "Rich, meaty tomato sauce simmered to perfection and tossed with al dente spaghetti. A timeless Italian favorite.",
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    tags: ["dinner", "pasta", "italian", "comfort-food", "family-friendly"],
    imageUrl: "https://images.unsplash.com/photo-1598866594230-a7c12756260f",
    ingredients: [
      { name: "Ground Beef", amount: 1.5, unit: "lbs" },
      { name: "Spaghetti", amount: 1, unit: "lb" },
      { name: "Crushed Tomatoes", amount: 28, unit: "oz" },
      { name: "Onion", amount: 1, unit: "large" },
      { name: "Carrots", amount: 2, unit: "medium" },
      { name: "Garlic", amount: 4, unit: "cloves" },
      { name: "Red Wine", amount: 0.5, unit: "cup" },
      { name: "Italian Seasoning", amount: 2, unit: "tsp" },
    ],
    instructions: [
      "Finely dice onion and carrots, mince garlic.",
      "Heat olive oil in a large pot over medium heat.",
      "Brown ground beef, breaking it up as it cooks, about 8 minutes.",
      "Add onion, carrots, and garlic, cooking until softened.",
      "Pour in red wine and let it simmer for 2 minutes.",
      "Add crushed tomatoes and Italian seasoning.",
      "Simmer sauce on low heat for 30 minutes, stirring occasionally.",
      "Cook spaghetti according to package directions.",
      "Toss pasta with sauce and serve with Parmesan cheese.",
    ],
    isPublic: true,
    difficulty: "medium" as RecipeDifficulty,
    calories: 560,
    protein: 32,
    carbs: 64,
    fat: 18,
    categoryIds: [],
  },
  {
    title: "Mediterranean Chicken Bowl",
    description:
      "Grilled chicken with quinoa, fresh vegetables, feta cheese, and a tangy lemon herb dressing. Healthy and delicious.",
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    tags: ["dinner", "bowl", "mediterranean", "healthy", "protein"],
    imageUrl: "https://images.unsplash.com/photo-1623428187425-5f6d46d85b3d",
    ingredients: [
      { name: "Chicken Breast", amount: 1.5, unit: "lbs" },
      { name: "Quinoa", amount: 1, unit: "cup" },
      { name: "Cherry Tomatoes", amount: 2, unit: "cups" },
      { name: "Cucumber", amount: 1, unit: "large" },
      { name: "Feta Cheese", amount: 0.5, unit: "cup" },
      { name: "Olives", amount: 0.5, unit: "cup" },
      { name: "Lemon Juice", amount: 0.25, unit: "cup" },
      { name: "Oregano", amount: 1, unit: "tsp" },
    ],
    instructions: [
      "Cook quinoa according to package directions and let cool slightly.",
      "Season chicken with salt, pepper, and oregano.",
      "Grill chicken for 6-7 minutes per side until cooked through.",
      "Let chicken rest, then slice into strips.",
      "Dice cucumber and halve cherry tomatoes.",
      "In a bowl, whisk together lemon juice, olive oil, and oregano for dressing.",
      "Build bowls with quinoa, grilled chicken, vegetables, olives, and feta.",
      "Drizzle with dressing and serve.",
    ],
    isPublic: true,
    difficulty: "medium" as RecipeDifficulty,
    calories: 460,
    protein: 42,
    carbs: 38,
    fat: 16,
    categoryIds: [],
  },
  {
    title: "One-Pan Pesto Chicken and Vegetables",
    description:
      "Juicy chicken breast with roasted vegetables and store-bought pesto. Minimal cleanup, maximum flavor.",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    tags: ["dinner", "one-pan", "easy", "chicken", "italian"],
    imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
    ingredients: [
      { name: "Chicken Breast", amount: 4, unit: "pieces" },
      { name: "Cherry Tomatoes", amount: 2, unit: "cups" },
      { name: "Zucchini", amount: 2, unit: "medium" },
      { name: "Red Onion", amount: 1, unit: "large" },
      { name: "Pesto", amount: 0.5, unit: "cup" },
      { name: "Olive Oil", amount: 2, unit: "tbsp" },
      { name: "Salt", amount: 1, unit: "tsp" },
      { name: "Black Pepper", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Cut zucchini into rounds and onion into wedges.",
      "Place chicken breasts on a large baking sheet.",
      "Arrange vegetables around the chicken.",
      "Drizzle everything with olive oil and season with salt and pepper.",
      "Spread pesto over chicken breasts.",
      "Roast for 25 minutes until chicken reaches 165°F.",
      "Serve hot, garnished with fresh basil if desired.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 380,
    protein: 38,
    carbs: 14,
    fat: 20,
    categoryIds: [],
  },
  {
    title: "Slow Cooker Beef Chili",
    description:
      "Hearty, warming chili packed with ground beef, beans, and spices. Set it and forget it for a perfect dinner.",
    prepTime: 15,
    cookTime: 240,
    servings: 8,
    tags: ["dinner", "slow-cooker", "comfort-food", "spicy", "meal-prep"],
    imageUrl: "https://images.unsplash.com/photo-1583032015627-932315163015",
    ingredients: [
      { name: "Ground Beef", amount: 2, unit: "lbs" },
      { name: "Kidney Beans", amount: 2, unit: "cans" },
      { name: "Diced Tomatoes", amount: 2, unit: "cans" },
      { name: "Onion", amount: 1, unit: "large" },
      { name: "Bell Peppers", amount: 2, unit: "large" },
      { name: "Chili Powder", amount: 3, unit: "tbsp" },
      { name: "Cumin", amount: 1, unit: "tbsp" },
      { name: "Garlic", amount: 4, unit: "cloves" },
    ],
    instructions: [
      "Brown ground beef in a skillet, breaking it up as it cooks.",
      "Drain excess fat and transfer beef to slow cooker.",
      "Dice onion and bell peppers, mince garlic.",
      "Add vegetables, beans, tomatoes, and all spices to slow cooker.",
      "Stir everything together thoroughly.",
      "Cover and cook on low for 6-8 hours or high for 3-4 hours.",
      "Taste and adjust seasoning before serving.",
      "Serve with shredded cheese, sour cream, and cornbread.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 420,
    protein: 32,
    carbs: 38,
    fat: 16,
    categoryIds: [],
  },
  {
    title: "Teriyaki Chicken Rice Bowl",
    description:
      "Tender chicken glazed with homemade teriyaki sauce served over fluffy rice with steamed vegetables.",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    tags: ["dinner", "asian", "bowl", "chicken", "easy"],
    imageUrl: "https://images.unsplash.com/photo-1555126634-323283e090fa",
    ingredients: [
      { name: "Chicken Thighs", amount: 1.5, unit: "lbs" },
      { name: "White Rice", amount: 2, unit: "cups" },
      { name: "Soy Sauce", amount: 0.5, unit: "cup" },
      { name: "Brown Sugar", amount: 0.25, unit: "cup" },
      { name: "Mirin", amount: 0.25, unit: "cup" },
      { name: "Broccoli", amount: 2, unit: "cups" },
      { name: "Carrots", amount: 2, unit: "medium" },
      { name: "Sesame Seeds", amount: 2, unit: "tbsp" },
    ],
    instructions: [
      "Cook rice according to package directions.",
      "In a small saucepan, combine soy sauce, brown sugar, and mirin.",
      "Simmer sauce for 5 minutes until slightly thickened.",
      "Cut chicken into bite-sized pieces.",
      "Cook chicken in a large skillet over medium-high heat for 8 minutes.",
      "Steam broccoli and sliced carrots for 5 minutes.",
      "Pour teriyaki sauce over cooked chicken and toss to coat.",
      "Build bowls with rice, teriyaki chicken, and vegetables.",
      "Garnish with sesame seeds and sliced green onions.",
    ],
    isPublic: true,
    difficulty: "easy" as RecipeDifficulty,
    calories: 520,
    protein: 38,
    carbs: 68,
    fat: 10,
    categoryIds: [],
  },
];

// TODO
// Fix macro counting in meal planning system(Currently is dividing by number of servings in the recipe)
// Improve on meal plan creation user can choose to start from existing plan or create a new one
// user Can choose how many meals per day they want to have
// add translations to planing page
// sidebar infinitive scroll for recipes

export { recipes };

export const getMockRecipeData = (): RecipeFormData => recipes[16];
