import { RecipeFormData } from "@/types/recipe";
import { recipeDifficultyEnum } from "@/types/recipe";

const recipes = [
  {
    title: "Spicy Chicken Stir-Fry",
    description:
      "A quick and delicious stir-fry with a spicy kick. Perfect for a weeknight dinner.",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    tags: ["spicy", "asian", "chicken", "quick"],
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    ingredients: [
      { name: "Chicken Breast", amount: 2, unit: "piece" },
      { name: "Broccoli Florets", amount: 2, unit: "cups" },
      { name: "Carrot", amount: 1, unit: "large" },
      { name: "Soy Sauce", amount: 0.25, unit: "cup" },
      { name: "Sriracha", amount: 2, unit: "tbsp" },
      { name: "Garlic", amount: 3, unit: "cloves" },
      { name: "Ginger", amount: 1, unit: "inch" },
      { name: "Sesame Oil", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Cut chicken into bite-sized pieces.",
      "Chop broccoli and slice carrots.",
      "Mince garlic and grate ginger.",
      "In a small bowl, mix soy sauce and sriracha.",
      "Heat sesame oil in a large skillet or wok over medium-high heat.",
      "Add chicken and cook until browned.",
      "Add broccoli and carrots to the skillet and cook for 3-5 minutes, until tender-crisp.",
      "Stir in the garlic and ginger and cook for another minute until fragrant.",
      "Pour the sauce over the stir-fry and toss to combine. Cook for 1-2 minutes until the sauce has thickened slightly.",
      "Serve immediately, garnished with sesame seeds if desired.",
    ],
    isPublic: true,
    difficulty: recipeDifficultyEnum.parse("easy"),
    calories: 200,
    protein: 20,
    carbs: 10,
    fat: 10,
    categoryIds: [], // Set to empty, will be populated dynamically in the form
  },
  {
    title: "Classic Greek Salad",
    description:
      "A refreshing Mediterranean salad with crisp vegetables and tangy feta cheese.",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    tags: ["vegetarian", "mediterranean", "healthy", "salad"],
    imageUrl: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe",
    ingredients: [
      { name: "Cucumber", amount: 1, unit: "large" },
      { name: "Tomatoes", amount: 4, unit: "medium" },
      { name: "Red Onion", amount: 1, unit: "medium" },
      { name: "Green Bell Pepper", amount: 1, unit: "medium" },
      { name: "Kalamata Olives", amount: 0.5, unit: "cup" },
      { name: "Feta Cheese", amount: 200, unit: "g" },
      { name: "Extra Virgin Olive Oil", amount: 0.25, unit: "cup" },
      { name: "Dried Oregano", amount: 1, unit: "tsp" },
    ],
    instructions: [
      "Slice cucumber into thick half-moons.",
      "Cut tomatoes into wedges.",
      "Slice red onion thinly.",
      "Cut bell pepper into rings.",
      "Combine vegetables in a large bowl.",
      "Add olives and crumbled feta cheese.",
      "Drizzle with olive oil and sprinkle with oregano.",
      "Toss gently and serve immediately.",
    ],
    isPublic: true,
    difficulty: recipeDifficultyEnum.parse("easy"),
    categoryIds: [],
  },
  {
    title: "Homemade Tiramisu",
    description:
      "A classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.",
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    tags: ["dessert", "italian", "no-bake", "coffee"],
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9",
    ingredients: [
      { name: "Ladyfinger Cookies", amount: 24, unit: "pieces" },
      { name: "Mascarpone Cheese", amount: 500, unit: "g" },
      { name: "Strong Coffee", amount: 1.5, unit: "cups" },
      { name: "Eggs", amount: 4, unit: "large" },
      { name: "Sugar", amount: 0.75, unit: "cup" },
      { name: "Cocoa Powder", amount: 2, unit: "tbsp" },
      { name: "Vanilla Extract", amount: 1, unit: "tsp" },
    ],
    instructions: [
      "Brew coffee and let it cool completely.",
      "Separate egg yolks and whites.",
      "Beat egg yolks with sugar until pale and creamy.",
      "Add mascarpone and vanilla to egg mixture.",
      "Beat egg whites until stiff peaks form and fold into mascarpone mixture.",
      "Dip ladyfingers briefly in coffee and layer in serving dish.",
      "Spread half the mascarpone mixture over ladyfingers.",
      "Repeat layers and dust with cocoa powder.",
      "Refrigerate for at least 4 hours before serving.",
    ],
    isPublic: true,
    difficulty: recipeDifficultyEnum.parse("easy"),
    calories: 200,
    protein: 20,
    carbs: 10,
    fat: 10,
    categoryIds: [],
  },
  {
    title: "Beef and Vegetable Stir-Fry",
    description:
      "A quick and flavorful weeknight dinner packed with tender beef and colorful vegetables.",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    tags: ["beef", "asian", "quick", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
    ingredients: [
      { name: "Beef Sirloin", amount: 500, unit: "g" },
      { name: "Broccoli", amount: 2, unit: "cups" },
      { name: "Red Bell Pepper", amount: 1, unit: "large" },
      { name: "Snap Peas", amount: 1, unit: "cup" },
      { name: "Soy Sauce", amount: 0.25, unit: "cup" },
      { name: "Oyster Sauce", amount: 2, unit: "tbsp" },
      { name: "Garlic", amount: 3, unit: "cloves" },
      { name: "Vegetable Oil", amount: 2, unit: "tbsp" },
    ],
    instructions: [
      "Slice beef thinly against the grain.",
      "Cut broccoli into florets and slice bell pepper.",
      "Mix soy sauce and oyster sauce in a small bowl.",
      "Heat oil in a wok over high heat.",
      "Stir-fry beef until browned, remove from wok.",
      "Add vegetables and garlic to wok, stir-fry until crisp-tender.",
      "Return beef to wok, add sauce mixture.",
      "Cook until sauce thickens, about 2 minutes.",
      "Serve hot over steamed rice.",
    ],
    isPublic: true,
    difficulty: recipeDifficultyEnum.parse("easy"),
    calories: 200,
    protein: 20,
    carbs: 10,
    fat: 10,
    categoryIds: [],
  },
  {
    title: "Mediterranean Quinoa Bowl",
    description:
      "A nutritious and colorful grain bowl packed with protein and fresh vegetables.",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    tags: ["vegetarian", "healthy", "mediterranean", "meal-prep"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    ingredients: [
      { name: "Quinoa", amount: 1, unit: "cup" },
      { name: "Cherry Tomatoes", amount: 2, unit: "cups" },
      { name: "Cucumber", amount: 1, unit: "medium" },
      { name: "Chickpeas", amount: 1, unit: "can" },
      { name: "Red Onion", amount: 0.5, unit: "medium" },
      { name: "Feta Cheese", amount: 100, unit: "g" },
      { name: "Lemon", amount: 1, unit: "whole" },
      { name: "Olive Oil", amount: 3, unit: "tbsp" },
    ],
    instructions: [
      "Cook quinoa according to package instructions.",
      "Halve cherry tomatoes and dice cucumber.",
      "Drain and rinse chickpeas.",
      "Finely dice red onion.",
      "Combine cooked quinoa with vegetables and chickpeas.",
      "Crumble feta cheese over the top.",
      "Squeeze lemon juice and drizzle olive oil.",
      "Season with salt and pepper to taste.",
      "Toss gently and serve at room temperature.",
    ],
    isPublic: true,
    difficulty: recipeDifficultyEnum.parse("easy"),
    calories: 200,
    protein: 20,
    carbs: 10,
    fat: 10,
    categoryIds: [],
  },
  {
    title: "Lemon Blueberry Pancakes",
    description:
      "Fluffy pancakes studded with fresh blueberries and brightened with lemon zest.",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    tags: ["breakfast", "brunch", "vegetarian", "sweet"],
    imageUrl: "https://images.unsplash.com/photo-1528207776546-365bb710ee93",
    ingredients: [
      { name: "All-Purpose Flour", amount: 1.5, unit: "cups" },
      { name: "Baking Powder", amount: 2, unit: "tsp" },
      { name: "Sugar", amount: 0.25, unit: "cup" },
      { name: "Milk", amount: 1.25, unit: "cups" },
      { name: "Eggs", amount: 2, unit: "large" },
      { name: "Butter", amount: 3, unit: "tbsp" },
      { name: "Blueberries", amount: 1, unit: "cup" },
      { name: "Lemon Zest", amount: 1, unit: "tbsp" },
    ],
    instructions: [
      "Whisk together flour, baking powder, and sugar.",
      "In another bowl, combine milk, eggs, and melted butter.",
      "Add wet ingredients to dry ingredients and mix until just combined.",
      "Fold in blueberries and lemon zest.",
      "Heat a griddle or non-stick pan over medium heat.",
      "Pour 1/4 cup batter for each pancake.",
      "Cook until bubbles form on surface, then flip.",
      "Cook other side until golden brown.",
      "Serve with maple syrup and extra blueberries.",
    ],
    isPublic: true,
    difficulty: recipeDifficultyEnum.parse("easy"),
    calories: 200,
    protein: 20,
    carbs: 10,
    fat: 10,
    categoryIds: [],
  },
  {
    title: "Garlic Herb Roasted Chicken",
    description:
      "Juicy roasted chicken with crispy skin, infused with garlic, rosemary, and thyme. Perfect for a family dinner.",
    prepTime: 15,
    cookTime: 75,
    servings: 6,
    tags: ["dinner", "main course", "protein", "comfort food"],
    imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6",
    ingredients: [
      { name: "Whole Chicken", amount: 1, unit: "whole (4-5 lbs)" },
      { name: "Olive Oil", amount: 3, unit: "tbsp" },
      { name: "Garlic Cloves", amount: 6, unit: "cloves" },
      { name: "Fresh Rosemary", amount: 3, unit: "sprigs" },
      { name: "Fresh Thyme", amount: 4, unit: "sprigs" },
      { name: "Lemon", amount: 1, unit: "whole" },
      { name: "Butter", amount: 2, unit: "tbsp" },
      { name: "Salt", amount: 2, unit: "tsp" },
      { name: "Black Pepper", amount: 1, unit: "tsp" },
      { name: "Paprika", amount: 1, unit: "tsp" },
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "Pat the chicken dry with paper towels.",
      "Mix olive oil, minced garlic, salt, pepper, and paprika in a small bowl.",
      "Rub the mixture all over the chicken, including under the skin.",
      "Stuff the cavity with lemon halves, rosemary, and thyme.",
      "Place butter pats under the breast skin.",
      "Tie the legs together with kitchen twine and tuck wing tips under.",
      "Place chicken breast-side up in a roasting pan.",
      "Roast for 1 hour 15 minutes, or until internal temperature reaches 165°F.",
      "Baste with pan juices every 20 minutes.",
      "Let rest for 10 minutes before carving.",
      "Serve with roasted vegetables or your favorite sides.",
    ],
    isPublic: true,
    difficulty: recipeDifficultyEnum.parse("medium"),
    calories: 350,
    protein: 42,
    carbs: 2,
    fat: 18,
    categoryIds: [],
  },
];

export { recipes };

export const getMockRecipeData = (): RecipeFormData => recipes[2];
